# Generated by Django 4.1.3 on 2023-07-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_ops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
