# Generated by Django 4.1.3 on 2023-07-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_ops', '0002_groups_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_subjects',
            },
        ),
    ]
