# Generated by Django 4.1.3 on 2023-07-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_ops', '0003_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_ops.groups')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_ops.subjects')),
            ],
            options={
                'db_table': 'school_teachers',
            },
        ),
    ]
