# Generated by Django 4.1.3 on 2023-07-22 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_ops', '0004_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=522)),
                ('last_name', models.CharField(max_length=522)),
                ('is_active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_ops.groups')),
            ],
            options={
                'db_table': 'school_students',
            },
        ),
    ]
