# Generated by Django 4.1.3 on 2023-07-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_ops', '0005_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mark', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_ops.students')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_ops.subjects')),
            ],
            options={
                'db_table': 'school_marks',
            },
        ),
    ]
